name: local_clickhouse_dbt
version: 1.0.0
config-version: 2

profile: local_clickhouse

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  local_clickhouse_dbt:
    +materialized: table
