prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  server:
    service:
      type: ClusterIP
    persistentVolume:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
