apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest-alpine
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-web
  template:
    metadata:
      labels:
        app: clickhouse-web
    spec:
      containers:
        - name: clickhouse-web
          image: spoonest/clickhouse-tabix-web-client:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: CH_NAME
              value: Local ClickHouse
            - name: CH_HOST
              value: clickhouse.clickhouse.svc.cluster.local
            - name: CH_PORT
              value: "8123"
            - name: CH_USER
              value: default
            - name: CH_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-web
spec:
  selector:
    app: clickhouse-web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
